[View in Colaboratory](https://colab.research.google.com/github/zuolinye/Tensorflow/blob/master/%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0.ipynb)

1. 激活函数（activation function）

有效避免纯线性组合，提高了模型的表达力，使模型具有更好的区分度

2. 偏置项bias

3. NN复杂度：多用NN层数和NN参数的个数表示
层数 = 隐藏层的层数 + 1个输出层

总参数 = 总W + 总b

优化：损失函数loss，学习率learning_rate，滑动平均ema，正则化regularization

In [1]:
#coding:utf-8
#预测多或预测少的影响一样
#0导入模块，生成数据集
import tensorflow as tf
import numpy as np
BATCH_SIZE = 8
SEED = 23455

rdm = np.random.RandomState(SEED)
X = rdm.rand(32,2)
Y_ = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

#1定义神经网络的输入、参数和输出，定义前向传播过程。
x = tf.placeholder(tf.float32, shape=(None, 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))
w1= tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#2定义损失函数及反向传播方法。
#定义损失函数为MSE,反向传播方法为梯度下降。
loss_mse = tf.reduce_mean(tf.square(y_ - y))
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss_mse)

#3生成会话，训练STEPS轮
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 20000
    for i in range(STEPS):
        start = (i*BATCH_SIZE) % 32
        end = (i*BATCH_SIZE) % 32 + BATCH_SIZE
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y_[start:end]})
        if i % 500 == 0:
            print "After %d training steps, w1 is: " % (i)
            print sess.run(w1), "\n"
    print "Final w1 is: \n", sess.run(w1)

After 0 training steps, w1 is: 
[[-0.80974597]
 [ 1.4852903 ]] 

After 500 training steps, w1 is: 
[[-0.46074435]
 [ 1.641878  ]] 

After 1000 training steps, w1 is: 
[[-0.21939856]
 [ 1.6984766 ]] 

After 1500 training steps, w1 is: 
[[-0.04415595]
 [ 1.7003176 ]] 

After 2000 training steps, w1 is: 
[[0.08942621]
 [1.673328  ]] 

After 2500 training steps, w1 is: 
[[0.19583553]
 [1.6322677 ]] 

After 3000 training steps, w1 is: 
[[0.28375748]
 [1.5854434 ]] 

After 3500 training steps, w1 is: 
[[0.35848638]
 [1.5374471 ]] 

After 4000 training steps, w1 is: 
[[0.4233252]
 [1.4907392]] 

After 4500 training steps, w1 is: 
[[0.48040032]
 [1.4465573 ]] 

After 5000 training steps, w1 is: 
[[0.5311361]
 [1.4054534]] 

After 5500 training steps, w1 is: 
[[0.57653254]
 [1.367594  ]] 

After 6000 training steps, w1 is: 
[[0.6173259]
 [1.3329402]] 

After 6500 training steps, w1 is: 
[[0.65408474]
 [1.3013425 ]] 

After 7000 training steps, w1 is: 
[[0.68726856]
 [1.2726018 ]] 

After 7500 t

In [2]:
#coding:utf-8
#酸奶成本1元， 酸奶利润9元
#预测少了损失大，故不要预测少，故生成的模型会多预测一些
#0导入模块，生成数据集
import tensorflow as tf
import numpy as np
BATCH_SIZE = 8
SEED = 23455
COST = 1
PROFIT = 9

rdm = np.random.RandomState(SEED)
X = rdm.rand(32,2)
Y = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

#1定义神经网络的输入、参数和输出，定义前向传播过程。
x = tf.placeholder(tf.float32, shape=(None, 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))
w1= tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#2定义损失函数及反向传播方法。
# 定义损失函数使得预测少了的损失大，于是模型应该偏向多的方向预测。
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_)*COST, (y_ - y)*PROFIT))
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

#3生成会话，训练STEPS轮。
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 3000
    for i in range(STEPS):
        start = (i*BATCH_SIZE) % 32
        end = (i*BATCH_SIZE) % 32 + BATCH_SIZE
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 500 == 0:
            print "After %d training steps, w1 is: " % (i)
            print sess.run(w1), "\n"
    print "Final w1 is: \n", sess.run(w1)


After 0 training steps, w1 is: 
[[-0.762993 ]
 [ 1.5095658]] 

After 500 training steps, w1 is: 
[[1.0235443]
 [1.0463371]] 

After 1000 training steps, w1 is: 
[[1.0174844]
 [1.0406414]] 

After 1500 training steps, w1 is: 
[[1.0211805]
 [1.0472372]] 

After 2000 training steps, w1 is: 
[[1.0179386]
 [1.041272 ]] 

After 2500 training steps, w1 is: 
[[1.0205938]
 [1.0390443]] 

Final w1 is: 
[[1.0296593]
 [1.0484141]]
